// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rltfsltmepnbcznhabnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdGZzbHRtZXBuYmN6bmhhYm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTkwMDMsImV4cCI6MjA2NDMzNTAwM30.yrvirSjOwW3J4mN6ZjcG6NC1NDA_j-dBqKxTA6HCaDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);